### ISSUE TITLE
[ENHANCEMENT] Add GitHub Actions labeler workflow for automated PR labeling

### ISSUE THREAD

**Issue by basher83** [basher83/ProxmoxMCP#35]
## Summary
Add GitHub Actions labeler workflow to automatically apply labels to pull requests based on changed file paths, branch names, and content patterns. This will improve PR categorization and reduce manual labeling overhead.

## Use Case
Currently, pull requests must be manually labeled which can be time-consuming and inconsistent. The actions/labeler workflow will automatically:
- Label PRs based on file path changes (e.g., docs/, src/, tests/)  
- Apply component-specific labels (server, config, tools, formatting, docker)
- Categorize by change type (dependencies, ci, security)
- Ensure consistent labeling across all pull requests

### 1. Add Labeler Workflow
Create `.github/workflows/labeler.yml`:
```yaml
name: Labeler
on: [pull_request_target]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
```

### 2. Add Labeler Configuration  
Create `.github/labeler.yml` with ProxmoxMCP-specific patterns:
```yaml
# Component Labels
'component:server':
  - changed-files:
    - any-glob-to-any-file: ['src/proxmox_mcp/server.py']

'component:config': 
  - changed-files:
    - any-glob-to-any-file: ['src/proxmox_mcp/config/**']

'component:tools':
  - changed-files: 
    - any-glob-to-any-file: ['src/proxmox_mcp/tools/**']

'component:formatting':
  - changed-files:
    - any-glob-to-any-file: ['src/proxmox_mcp/formatting/**']

'component:docker':
  - changed-files:
    - any-glob-to-any-file: ['Dockerfile', 'compose.yaml', '.dockerignore']

'documentation':
  - changed-files:
    - any-glob-to-any-file: ['docs/**', '*.md', '.github/**/*.md']
```

## ProxmoxMCP Integration
- **Architectural Considerations**: Integrates with existing GitHub Actions workflows (autofix.ci, claude-auto-review)
- **Security Implications**: Uses `pull_request_target` for external PRs with minimal permissions
- **Performance Impact**: Minimal - runs only on PR events with fast path-based matching
- **Breaking Changes**: None - purely additive automation

## Acceptance Criteria
- [ ] Labeler workflow file created and functional
- [ ] Labeler configuration covers all ProxmoxMCP components
- [ ] Integration tested with sample PRs
- [ ] Documentation updated with labeling guidelines  
- [ ] No conflicts with existing automation workflows

## Implementation Notes
- **Dependencies**: GitHub Actions labeler v5 (latest stable)
- **Testing Requirements**: Test with PRs affecting different components
- **Documentation Updates**: Update CONTRIBUTING.md with auto-labeling info

## Benefits
- **Improved Consistency**: Automatic labeling reduces human error
- **Better Organization**: PRs properly categorized from creation
- **Enhanced Workflow**: Maintainers can filter and prioritize more effectively
- **Developer Experience**: Contributors see immediate feedback on PR scope
- **Integration Ready**: Works seamlessly with existing ProxmoxMCP labels

## Timeline
Medium priority - enhances workflow efficiency without blocking development
