### ISSUE TITLE
[ENHANCEMENT] Enhance autofix.ci workflow with improved performance and robustness

### ISSUE THREAD

**Issue by basher83** [basher83/ProxmoxMCP#38]
## Summary
Enhance the existing autofix.ci workflow with improved performance through job parallelization, better caching strategies, and more robust error handling while maintaining compatibility with the current ProxmoxMCP development workflow.

## Use Case
The current autofix.ci workflow runs all quality checks sequentially in a single job, which can be slow and doesn't provide granular feedback on specific failures. The enhanced workflow would:

- Provide faster feedback through parallel job execution
- Improve cache utilization for dependencies and virtual environments
- Add optional test execution when tests exist
- Provide better error reporting and job status visibility
- Maintain security best practices with appropriate permissions

### Technical Details
- **Affected Components**: CI/CD pipeline, development workflow
- **GitHub Actions Changes**: Multi-job workflow with parallel execution
- **Caching Strategy**: UV virtual environment caching and pip dependency caching
- **Security Enhancements**: Concurrency control to cancel redundant runs

### Enhanced Workflow Features
```yaml
# Key improvements in the proposed workflow:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write  # Required for autofix.ci to commit changes
  pull-requests: write  # Required for PR comments

jobs:
  lint-and-format:     # Main autofix.ci job
  type-check:          # Parallel type checking
  test:                # Optional test execution
  all-checks:          # Summary status job
```

## ProxmoxMCP Integration
- **Architectural Considerations**: Maintains compatibility with existing development commands
- **Performance Impact**: Faster CI feedback through parallel execution and improved caching
- **Security Implications**: Enhanced permissions for autofix.ci functionality while maintaining security
- **Breaking Changes**: None - fully backward compatible

### Current Limitations:
- Sequential execution of all checks in single job
- Basic caching without UV virtual environment optimization
- Limited error granularity
- No test execution integration
- Missing concurrency control

### Enhanced Benefits:
- **Parallel Execution**: lint-and-format, type-check, and test jobs run simultaneously
- **Advanced Caching**: UV virtual environment caching reduces setup time
- **Granular Feedback**: Individual job status for each check type
- **Optional Testing**: Automatic test execution when tests exist
- **Concurrency Control**: Cancels redundant runs on new pushes
- **Status Summary**: all-checks job provides overall pass/fail status

## Acceptance Criteria
- [ ] Workflow maintains full compatibility with autofix.ci functionality
- [ ] Parallel jobs improve overall execution time
- [ ] UV virtual environment caching works correctly
- [ ] Type checking runs independently and reports issues
- [ ] Optional test job executes only when tests exist
- [ ] Concurrency control cancels redundant workflow runs
- [ ] All existing quality checks (black, ruff, mypy) continue to work
- [ ] autofix.ci continues to commit automatic fixes
- [ ] Workflow permissions are appropriately scoped

## Implementation Notes
- **Dependencies**: No new external dependencies required
- **Testing Requirements**: Verify workflow execution in CI environment
- **Documentation Updates**: Update development workflow documentation

## Configuration Changes
The enhanced workflow uses:
- Python 3.12 (upgrade from 3.10 for better performance)
- UV virtual environment caching with cache keys
- Improved step organization and naming
- Better error handling with conditional execution
- Enhanced output formatting for CI logs

## Performance Improvements
- **Caching Strategy**: UV venv caching reduces dependency installation time
- **Parallel Execution**: Multiple jobs run simultaneously instead of sequentially
- **Selective Testing**: Tests only run when test files exist
- **Concurrency Control**: Prevents resource waste from redundant runs

## Security Considerations
- Maintains secure autofix.ci integration patterns
- Uses pinned action versions for security
- Appropriate permission scoping (contents: write, pull-requests: write)
- Safe for external contributor PRs through standard triggers

## Timeline
Medium priority enhancement that can be implemented alongside normal development workflow improvements.

**Comment by basher83** [comment]
Proposed enhancement:

```
name: autofix.ci  # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: [ "main" ]

# Cancel redundant runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write  # Required for autofix.ci to commit changes
  pull-requests: write  # Required for PR comments
1
jobs:
  # Fast checks that can run in parallel
  lint-and-format:
    runs-on: ubuntu-latest
    outputs:
      changes-made: ${{ steps.autofix.outputs.changes-made }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'  # Cache pip dependencies

      - name: Install UV
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      # Cache UV virtual environment
      - name: Cache UV venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            venv-${{ runner.os }}-

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run black formatter
        run: |
          uv run black . --check --diff || uv run black .

      - name: Run ruff with auto-fix
        run: |
          uv run ruff check . --fix --exit-zero

      # Only run autofix if this is the main job
      - name: Apply fixes
        id: autofix
        uses: autofix-ci/action@ff86a557419858bb967097bfc916833f5647fa8c

  # Type checking runs separately for faster feedback
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install UV
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: Cache UV venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            venv-${{ runner.os }}-

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run mypy type checking
        run: |
          uv run mypy . || true

  # Optional: Run tests if they exist
  test:
    runs-on: ubuntu-latest
    if: hashFiles('tests/**/*.py') != ''  # Only run if tests exist
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install UV
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: Cache UV venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            venv-${{ runner.os }}-

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run tests
        run: |
          uv run pytest -v --tb=short

  # Summary job that requires all checks to pass
  all-checks:
    runs-on: ubuntu-latest
    needs: [lint-and-format, type-check]
    if: always()
    steps:
      - name: Check all jobs status
        run: |
          if [[ "${{ needs.lint-and-format.result }}" != "success" || "${{ needs.type-check.result }}" != "success" ]]; then
            echo "One or more checks failed"
            exit 1
          else
            echo "All checks passed!"
          fi
```
