### ISSUE TITLE
[BUG] Fix hashFiles function usage in autofix.yml workflow

### ISSUE THREAD

**Issue by basher83** [basher83/ProxmoxMCP#40]
## Bug Description
The autofix.yml GitHub workflow is failing with a validation error due to incorrect usage of the `hashFiles` function in a job-level `if` condition.

## Steps to Reproduce
1. Push any commit to trigger the GitHub workflow
2. Check the Actions tab for workflow validation errors
3. Observe the error on line 99 of `.github/workflows/autofix.yml`

## Expected Behavior
The workflow should run successfully without validation errors and conditionally execute the test job only when test files exist.

## Actual Behavior
The workflow fails validation with the error:
```
Invalid workflow file: .github/workflows/autofix.yml#L99
The workflow is not valid. .github/workflows/autofix.yml (Line: 99, Col: 9): Unrecognized function: 'hashFiles'. Located at position 1 within expression: hashFiles('tests/**/*.py') != ''
```

## Environment
- **ProxmoxMCP Version**: Current main branch
- **Proxmox Version**: N/A (workflow issue)
- **Python Version**: N/A (workflow issue)
- **Operating System**: GitHub Actions (ubuntu-latest)
- **Deployment Method**: GitHub Actions CI/CD

## Logs/Error Messages
```
Invalid workflow file: .github/workflows/autofix.yml#L99
The workflow is not valid. .github/workflows/autofix.yml (Line: 99, Col: 9): Unrecognized function: 'hashFiles'. Located at position 1 within expression: hashFiles('tests/**/*.py') != ''
```

## Additional Context
The issue is on line 99 where we have:
```yaml
test:
  runs-on: ubuntu-latest
  if: hashFiles('tests/**/*.py') != ''
```

The `hashFiles` function cannot be used directly in job-level `if` conditions in GitHub Actions. It's only available in specific contexts.

## Possible Solution
Replace the job-level condition with a step-level check:
```yaml
test:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - name: Check for test files
      id: check-tests
      run: |
        if find tests -name "*.py" -type f | grep -q .; then
          echo "tests-exist=true" >> $GITHUB_OUTPUT
        else
          echo "tests-exist=false" >> $GITHUB_OUTPUT
        fi
    - name: Set up Python
      if: steps.check-tests.outputs.tests-exist == 'true'
      # ... rest of setup
```
