### ISSUE TITLE
[DOCKER] Phase 3: Release Automation and Supply Chain Security

### ISSUE THREAD

**Issue by basher83** [basher83/ProxmoxMCP#86]
## Summary

Implement comprehensive release automation with semantic versioning, container signing, and supply chain security features. This is Phase 3 of the Docker implementation strategy.

## Goals

- Automate semantic versioning and releases
- Implement container signing and attestation
- Generate Software Bill of Materials (SBOM)
- Create enterprise deployment artifacts

### Release Automation Workflow

- [ ] **Create `.github/workflows/release.yml`**
  - Automated semantic versioning with conventional commits
  - Changelog generation from commit history
  - Multi-platform container publishing
  - GitHub release creation with artifacts

- [ ] **Container signing implementation**
  - Cosign integration for container signing
  - Keyless signing with GitHub OIDC
  - Signature verification documentation
  - Attestation generation for build provenance

- [ ] **Supply chain security**
  - SBOM generation with Syft/Anchore
  - Provenance attestation creation
  - Security artifact publishing
  - Vulnerability database integration

### Kubernetes Deployment Artifacts

- [ ] **Basic Kubernetes manifests**
  - Deployment, Service, ConfigMap, Secret templates
  - Resource limits and security contexts
  - Health checks and readiness probes
  - Multi-environment configurations

- [ ] **Helm chart creation** (foundation)
  - Basic Helm chart structure
  - Configurable values.yaml
  - Template validation
  - Chart documentation

### Release Management

- [ ] **Version management system**
  - Semantic versioning validation
  - Container tag management (major.minor, major, latest)
  - Release channel strategy
  - Compatibility matrix documentation

- [ ] **Registry management**
  - Multi-registry publishing (GHCR primary)
  - Container retention policies
  - Registry access control
  - Image vulnerability tracking

### Release Workflow Features
```yaml
name: Release

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      security-events: write
      id-token: write  # For keyless signing
```

### Container Signing
```yaml
- name: Install cosign
  uses: sigstore/cosign-installer@v3

- name: Sign container image
  run:  < /dev/null | 
    cosign sign --yes ghcr.io/basher83/proxmox-mcp@${{ steps.build.outputs.digest }}
  env:
    COSIGN_EXPERIMENTAL: 1
```

### SBOM Generation
```yaml
- name: Generate SBOM
  uses: anchore/sbom-action@v0
  with:
    image: ghcr.io/basher83/proxmox-mcp:${{ github.ref_name }}
    output-file: sbom.spdx.json
    format: spdx-json

- name: Upload SBOM
  uses: actions/upload-artifact@v4
  with:
    name: sbom-${{ github.ref_name }}
    path: sbom.spdx.json
```

### Supply Chain Security
- **Container Signing**: Keyless signing with cosign and Sigstore
- **SBOM Generation**: Software Bill of Materials in SPDX format
- **Provenance Attestation**: Build provenance with GitHub attestations
- **Vulnerability Tracking**: Container security scanning with historical data

### Kubernetes Security
```yaml
securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  capabilities:
    drop: ["ALL"]
  readOnlyRootFilesystem: true
```

### Release Security
- **Automated security scanning**: Pre-release vulnerability checks
- **Signed releases**: All release artifacts are signed
- **Provenance tracking**: Complete build chain attestation
- **Access control**: Controlled release permissions

## Success Criteria

- [ ] ✅ Releases are automatically created with proper versioning
- [ ] ✅ Containers are signed and have SBOM attached
- [ ] ✅ Kubernetes deployment works out of the box
- [ ] ✅ Documentation covers all deployment scenarios
- [ ] ✅ Security scanning passes for all release artifacts
- [ ] ✅ Changelog is automatically generated and accurate

### Version Strategy
```
ProxmoxMCP v1.0.0    →  Container v1.0.0 + latest tag
ProxmoxMCP v1.0.1    →  Container v1.0.1, v1.0, v1 tags
ProxmoxMCP v1.1.0    →  Container v1.1.0, v1.1, v1 tags
```

### Container Tags
- `ghcr.io/basher83/proxmox-mcp:v1.0.0` (exact version)
- `ghcr.io/basher83/proxmox-mcp:v1.0` (minor version)
- `ghcr.io/basher83/proxmox-mcp:v1` (major version)
- `ghcr.io/basher83/proxmox-mcp:latest` (latest stable)

### Release Validation
- Full test suite execution
- Security scanning completion
- Multi-architecture build verification
- Container functionality testing

## Related Documentation

- [Docker Implementation Plan](docs/deployment/docker-implementation.md) - Release Process section
- [Docker CI/CD Documentation](docs/development/docker-cicd.md) - Release Automation section
- [Docker Deployment Guide](docs/deployment/docker-deployment.md) - Kubernetes section

## Dependencies

- **Prerequisite**: Issue #85 (Phase 2: Multi-Architecture Support)
- **Required**: Working multi-arch builds and security scanning

## Estimated Timeline

**Target Completion**: Week 3 of Docker implementation
**Effort**: Medium (1-2 days)
**Dependencies**: Phase 2 completion

## Follow-up Issues

This issue is part of the 4-phase Docker implementation:
- **Phase 1**: Basic CI/CD Implementation (Issue #84)
- **Phase 2**: Multi-Architecture Support Enhancement (Issue #85)
- **Phase 3** (this issue): Release Automation and Supply Chain Security
- **Phase 4**: Production Hardening
